import { marked } from "marked";

/**
 * Converts trusted application-owned Markdown into a full HTML document.
 *
 * Security note: the MVP stores Markdown written by authenticated users and
 * generated by our AI pipeline. Before supporting public multi-tenant embeds,
 * add a strict HTML sanitizer such as DOMPurify/rehype-sanitize at this layer.
 */
export function renderDocumentHtml(input: {
  title: string;
  markdown: string;
  exportedAt?: Date;
}) {
  const body = marked.parse(input.markdown || "", { async: false });
  const exportedAt = input.exportedAt ?? new Date();
  const escapedTitle = escapeHtml(input.title || "Untitled document");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapedTitle}</title>
  <style>
    :root { color-scheme: light; }
    body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f8fafc; color: #0f172a; }
    main { max-width: 860px; margin: 48px auto; padding: 48px; background: white; border: 1px solid #e2e8f0; border-radius: 24px; box-shadow: 0 20px 60px rgba(15, 23, 42, 0.08); }
    header { margin-bottom: 32px; padding-bottom: 24px; border-bottom: 1px solid #e2e8f0; }
    h1 { margin: 0; font-size: 36px; line-height: 1.1; letter-spacing: -0.03em; }
    .meta { margin-top: 12px; color: #64748b; font-size: 14px; }
    article { font-size: 16px; line-height: 1.75; }
    article h1, article h2, article h3 { line-height: 1.25; margin-top: 2em; letter-spacing: -0.02em; }
    article h2 { border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
    article pre { overflow: auto; padding: 16px; border-radius: 12px; background: #0f172a; color: #e2e8f0; }
    article code { padding: 2px 5px; border-radius: 6px; background: #f1f5f9; }
    article pre code { padding: 0; background: transparent; }
    article blockquote { margin: 24px 0; padding: 12px 20px; border-left: 4px solid #94a3b8; background: #f8fafc; color: #334155; }
    article table { width: 100%; border-collapse: collapse; margin: 24px 0; }
    article th, article td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
    article img { max-width: 100%; border-radius: 12px; border: 1px solid #e2e8f0; }
    @media print { body { background: white; } main { margin: 0; max-width: none; box-shadow: none; border: 0; border-radius: 0; } }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>${escapedTitle}</h1>
      <p class="meta">Exported ${exportedAt.toISOString()}</p>
    </header>
    <article>${body}</article>
  </main>
</body>
</html>`;
}

export function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
