# Generated by Django 1.9.7 on 2017-05-31 18:40
from django.db import migrations

import kalanfa.core.fields


class Migration(migrations.Migration):
    dependencies = [("logger", "0002_auto_20170518_1031")]

    operations = [
        migrations.AlterField(
            model_name="usersessionlog",
            name="last_interaction_timestamp",
            field=kalanfa.core.fields.DateTimeTzField(blank=True, null=True),
        )
    ]
