# Generated by Django 3.2.25 on 2024-05-27 19:19
import django.db.models.deletion
from django.db import migrations
from django.db import models

import kalanfa.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0026_update_language_code_nyn_to_ny"),
        ("exams", "0007_bump_data_model_version_to_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="date_created",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="DraftExam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("question_count", models.IntegerField()),
                (
                    "question_sources",
                    kalanfa.core.fields.JSONField(blank=True, default=[]),
                ),
                ("seed", models.IntegerField(default=1)),
                ("learners_see_fixed_order", models.BooleanField(default=False)),
                ("data_model_version", models.SmallIntegerField(default=3)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "assignments",
                    kalanfa.core.fields.JSONField(blank=True, default=list),
                ),
                (
                    "learner_ids",
                    kalanfa.core.fields.JSONField(blank=True, default=list),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draftexams",
                        to="kalanfaauth.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draftexams",
                        to="kalanfaauth.facilityuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
