/* Build file for kalanfa package */
const fs = require('node:fs');
const path = require('node:path');
const { writeSourceToFile } = require('kalanfa-format');
const glob = require('kalanfa-glob');
const { generateApiKeys } = require('kalanfa-build/src/apiSpecExportTools');

const apiSpecHeader = `/* eslint-disable import-x/no-commonjs */
/*
 * This file defines the API for the core Kalanfa app.
 * This file is automatically generated using the kalanfa package.json
 * exports and exposes fields by the kalanfa-build package.
 */

`;

function rebuildApiSpec() {
  // First we read the directory structure of the kalanfa folder to infer the list of modules
  // that are available to be imported.
  const kalanfaFolder = path.resolve(__dirname, './kalanfa');
  const kalanfaFiles = glob
    .sync(`${kalanfaFolder}/**/*.{js,vue}`, {
      ignore: ['**/internal/**', '**/__tests__/**', '**/__mocks__/**', '**/node_modules/**'],
    })
    .map(f => {
      const { dir, name } = path.parse(f);
      return path.join(dir, name);
    })
    .map(f => f.replace(kalanfaFolder, ''))
    .map(f => f.replace(/\/index$/, ''))
    .sort();
  // Then we generate the list of modules that are exposed in the kalanfa package.json
  const newApiSpec = {};
  for (const key of kalanfaFiles) {
    const specValue = '.' + key;
    // When we are able to move everything into a src folder
    // we can update the right hand side of this
    newApiSpec[specValue] = specValue === '.' ? './index' : specValue;
  }
  newApiSpec['./package.json'] = './package.json';
  const kalanfaPackageJsonFilePath = path.resolve(__dirname, './kalanfa/package.json');
  const kalanfaPackageJson = JSON.parse(fs.readFileSync(kalanfaPackageJsonFilePath));
  const updatedKalanfaPackageJson = {
    ...kalanfaPackageJson,
    exports: newApiSpec,
  };
  writeSourceToFile(kalanfaPackageJsonFilePath, JSON.stringify(updatedKalanfaPackageJson, null, 2));
  const apiSpecFilePath = path.resolve(__dirname, './kalanfa/internal/apiSpec.js');
  const updatedApiKeys = generateApiKeys(
    updatedKalanfaPackageJson.exports,
    updatedKalanfaPackageJson.exposes || [],
  );
  let apiSpecContent = apiSpecHeader;
  apiSpecContent += 'export default {\n';
  for (const key of updatedApiKeys) {
    apiSpecContent += `  '${key}': require('${key}'),\n`;
  }
  apiSpecContent += '};\n';
  writeSourceToFile(apiSpecFilePath, apiSpecContent);
}

rebuildApiSpec();
