"""baseline schema

Revision ID: 88a2f9e599a4
Revises: 
Create Date: 2026-07-04 10:00:16.551099
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '88a2f9e599a4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # PostGIS 3.6 on PostgreSQL 18 (fallback: 3.5 on 17) — required for events.location.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'EVENT_ORGANIZER', 'BOX_OFFICE_STAFF', 'SECURITY_GUARD', 'ATTENDEE', name='user_role'), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sa.String(length=300), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_events_window')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    # idx_events_location (GIST) is created by the Geometry column itself during create_table.
    op.create_index('ix_events_org_starts', 'events', ['organization_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index('ix_events_published_created', 'events', ['is_published', 'created_at', 'id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_webauthn_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_credentials')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_webauthn_credentials_credential_id'))
    )
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('badges',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MANAGEMENT_TEAM', 'SECURITY_STAFF', 'CONTRACTORS', 'VIP_VISITORS', 'STANDARD_ATTENDEE', name='badge_type'), nullable=False),
    sa.Column('access_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nfc_uid', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('pqc_signature', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_badges_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_badges_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badges_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges')),
    sa.UniqueConstraint('nfc_uid', name=op.f('uq_badges_nfc_uid')),
    sa.UniqueConstraint('qr_token', name=op.f('uq_badges_qr_token'))
    )
    op.create_index(op.f('ix_badges_event_id'), 'badges', ['event_id'], unique=False)
    op.create_index(op.f('ix_badges_organization_id'), 'badges', ['organization_id'], unique=False)
    op.create_table('scan_logs',
    sa.Column('subject_type', sa.Enum('ticket', 'badge', name='scan_subject'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.Enum('accepted', 'rejected', 'duplicate', name='scan_result'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('scanned_by', sa.Uuid(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_scan_logs_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], name=op.f('fk_scan_logs_scanned_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_logs'))
    )
    op.create_index('ix_scan_logs_event_time', 'scan_logs', ['event_id', 'scanned_at'], unique=False)
    op.create_table('ticket_tiers',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('sales_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity >= 0', name=op.f('ck_ticket_tiers_capacity_nonneg')),
    sa.CheckConstraint('price_cents >= 0', name=op.f('ck_ticket_tiers_price_nonneg')),
    sa.CheckConstraint('sold_count >= 0 AND sold_count <= capacity', name=op.f('ck_ticket_tiers_no_oversell')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_tiers_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_tiers'))
    )
    op.create_index(op.f('ix_ticket_tiers_event_id'), 'ticket_tiers', ['event_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_payments_event_id_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tier_id'], ['ticket_tiers.id'], name=op.f('fk_payments_tier_id_ticket_tiers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('stripe_checkout_session_id', name=op.f('uq_payments_stripe_checkout_session_id')),
    sa.UniqueConstraint('stripe_payment_intent_id', name=op.f('uq_payments_stripe_payment_intent_id')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_payments_user_idem')
    )
    op.create_index(op.f('ix_payments_event_id'), 'payments', ['event_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('created', 'valid', 'used', 'expired', 'refunded', name='ticket_status'), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('pqc_signature', sa.LargeBinary(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tickets_event_id_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tickets_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_tickets_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tier_id'], ['ticket_tiers.id'], name=op.f('fk_tickets_tier_id_ticket_tiers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('qr_token', name=op.f('uq_tickets_qr_token'))
    )
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index('ix_tickets_owner_created', 'tickets', ['owner_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_tickets_owner_id'), 'tickets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tickets_payment_id'), 'tickets', ['payment_id'], unique=False)
    op.create_index(op.f('ix_tickets_tier_id'), 'tickets', ['tier_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('created', 'valid', 'used', 'expired', 'refunded', name='ticket_status'), nullable=True),
    sa.Column('to_status', sa.Enum('created', 'valid', 'used', 'expired', 'refunded', name='ticket_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ticket_status_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_status_history_ticket_id_tickets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_status_history'))
    )
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement: ticket_status_history and scan_logs are audit
    # trails (§3 / NIS2) — UPDATE and DELETE are rejected at the database level.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ems_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("ticket_status_history", "scan_logs"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION ems_forbid_mutation()
            """
        )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ticket_status_history_append_only ON ticket_status_history")
    op.execute("DROP TRIGGER IF EXISTS scan_logs_append_only ON scan_logs")
    op.execute("DROP FUNCTION IF EXISTS ems_forbid_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_tickets_tier_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_payment_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_owner_id'), table_name='tickets')
    op.drop_index('ix_tickets_owner_created', table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_event_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_ticket_tiers_event_id'), table_name='ticket_tiers')
    op.drop_table('ticket_tiers')
    op.drop_index('ix_scan_logs_event_time', table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_badges_organization_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_event_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index('ix_events_published_created', table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index('ix_events_org_starts', table_name='events')
    op.drop_table('events')  # drops idx_events_location with it
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    for enum_name in (
        'ticket_status', 'payment_status', 'badge_type',
        'scan_subject', 'scan_result', 'user_role',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
