import Link from "next/link";
import { Button } from "@/components/ui/button";

export function SharedDocumentToolbar({ token }: { token: string }) {
  return (
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4 shadow-sm">
      <div>
        <p className="text-sm font-semibold text-slate-900">Shared documentation</p>
        <p className="text-xs text-slate-500">Read-only public view generated by AI Documentation Generator.</p>
      </div>
      <div className="flex gap-2">
        <Link href={`/api/share/${token}/download/markdown`}><Button variant="secondary">Markdown</Button></Link>
        <Link href={`/api/share/${token}/download/html`}><Button variant="secondary">HTML</Button></Link>
      </div>
    </div>
  );
}
