#!/usr/bin/env python3
"""Generate the Android offline-toolkit data assets from canonical sources.

Exports, into ``android/app/src/main/assets/offline/data.js``:

* the transliteration tables (``app/nko/tables.py``) so the JS engine is
  guaranteed to use byte-identical mappings to the Python engine,
* the alphabet view (``app/nko/block.py``) for the offline alphabet table,
* the full French→N'Ko lexicon plus its Bambara romanization for offline
  dictionary lookup.

Run from ``nko-voice-transcriptor/``:  python scripts/build_offline_assets.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
os.environ.setdefault("NKO_SECRET_KEY", "offline-asset-build-0123456789abcdef00")

from app.dictionary import get_dictionary  # noqa: E402
from app.langpack.registry import _romanize_nko  # noqa: E402
from app.nko import block, tables  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "android/app/src/main/assets/offline"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    data = {
        "vowels": tables.VOWELS,
        "consonants": tables.CONSONANTS,
        "digraphs": tables.DIGRAPHS,
        "normalizations": tables.NORMALIZATIONS,
        "digits": tables.DIGITS,
        "punctuation": tables.PUNCTUATION,
        "nkoNSyllabic": tables.NKO_N_SYLLABIC,
        "nkoNasal": tables.NKO_NASAL,
        "alphabet": block.alphabet(),
    }
    lexicon = [
        {"fr": e.fr, "bm": _romanize_nko(e.nko), "nko": e.nko, "cat": e.cat}
        for e in get_dictionary().entries
    ]

    js = (
        "// Generated by scripts/build_offline_assets.py — do not edit by hand.\n"
        "// Data: app/nko/tables.py, app/nko/block.py, app/data/lexicon-fr-nko.json\n"
        "// Lexicon (c) NKo Wuruki / N'Ko Institute — see app/data/NOTICE.md.\n"
        f"const NKO_DATA = {json.dumps(data, ensure_ascii=False)};\n"
        f"const NKO_LEXICON = {json.dumps(lexicon, ensure_ascii=False)};\n"
    )
    (OUT / "data.js").write_text(js, encoding="utf-8")
    size_mb = (OUT / "data.js").stat().st_size / 1e6
    print(f"wrote {OUT / 'data.js'}: {len(lexicon)} lexicon entries, {size_mb:.1f} MB")


if __name__ == "__main__":
    main()
