# Generated by Django 1.11.29 on 2022-10-26 18:13
from django.db import migrations

import kalanfa.core.device.models
import kalanfa.core.fields
import kalanfa.core.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0016_osuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="extra_settings",
            field=kalanfa.core.fields.JSONField(
                default=kalanfa.core.device.models.extra_settings_default_values,
                validators=[
                    kalanfa.core.utils.validators.JSON_Schema_Validator(
                        kalanfa.core.device.models.extra_settings_schema
                    )
                ],
            ),
        ),
    ]
