import type { GeneratedDocument } from "@/lib/validators/document";

/** Converts the AI JSON payload into readable Markdown that can be edited/exported. */
export function generatedDocumentToMarkdown(doc: GeneratedDocument) {
  const lines: string[] = [];
  lines.push(`# ${doc.title}`);
  lines.push("");
  lines.push(doc.summary);
  lines.push("");
  lines.push(`**Document type:** ${doc.document_type.replaceAll("_", " ")}`);
  lines.push(`**Audience:** ${doc.audience.replaceAll("_", " ")}`);
  lines.push(`**Confidence:** ${Math.round(doc.confidence_score * 100)}%`);

  if (doc.detected_ui.visible_elements.length || doc.detected_ui.buttons.length || doc.detected_ui.navigation_items.length) {
    lines.push("", "## Detected interface");
    if (doc.detected_ui.app_or_page_name) lines.push(`- Page/app: ${doc.detected_ui.app_or_page_name}`);
    if (doc.detected_ui.primary_goal) lines.push(`- Primary goal: ${doc.detected_ui.primary_goal}`);
    doc.detected_ui.visible_elements.forEach((item) => lines.push(`- Visible element: ${item}`));
    doc.detected_ui.buttons.forEach((item) => lines.push(`- Button: ${item}`));
    doc.detected_ui.navigation_items.forEach((item) => lines.push(`- Navigation: ${item}`));
  }

  lines.push("", "## Steps");
  doc.steps.forEach((step, index) => {
    lines.push("");
    lines.push(`### ${step.order || index + 1}. ${step.title}`);
    lines.push(step.instruction);
    lines.push("");
    lines.push(`**Expected result:** ${step.expected_result}`);
    if (step.ui_elements.length) lines.push(`**UI elements:** ${step.ui_elements.join(", ")}`);
    if (step.tip) lines.push(`> Tip: ${step.tip}`);
  });

  if (doc.tips.length) {
    lines.push("", "## Tips");
    doc.tips.forEach((tip) => lines.push(`- ${tip}`));
  }

  if (doc.warnings.length) {
    lines.push("", "## Warnings");
    doc.warnings.forEach((warning) => lines.push(`- ${warning}`));
  }

  if (doc.faq.length) {
    lines.push("", "## FAQ");
    doc.faq.forEach((item) => {
      lines.push(`### ${item.question}`);
      lines.push(item.answer);
    });
  }

  lines.push("", "---", `Generated by ${doc.metadata.provider} / ${doc.metadata.model} on ${doc.metadata.generated_at}`);
  return lines.join("\n");
}
