import Foundation

enum TutorAspect: String, Codable, CaseIterable, Identifiable {
    case answer, tafsir, tajweed, followUp

    var id: String { rawValue }

    var title: String {
        switch self {
        case .answer: "Answer"
        case .tafsir: "Tafsir"
        case .tajweed: "Tajweed"
        case .followUp: "Explore further"
        }
    }

    var icon: String {
        switch self {
        case .answer: "text.bubble.fill"
        case .tafsir: "book.fill"
        case .tajweed: "waveform"
        case .followUp: "lightbulb.fill"
        }
    }
}

/// One aspect of a tutor response (each generated by a separate parallel call).
struct TutorAspectResult: Codable, Identifiable {
    let aspect: TutorAspect
    let text: String?
    let error: String?
    var id: String { aspect.rawValue }
}

/// Response of `POST /tutor/ask`.
struct TutorResponse: Codable {
    struct Usage: Codable {
        let inputTokens: Int
        let outputTokens: Int
    }

    let question: String
    let aspects: [TutorAspectResult]
    let usage: Usage
    let latencyMs: Int
}
