# Generated by Django 3.2.25 on 2026-07-12 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kalanfaauth', '0035_facilitydataset_picture_password_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierEleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('nationalite', models.CharField(blank=True, default='Malienne', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('etablissement_precedent', models.CharField(blank=True, max_length=200)),
                ('certificat_transfert', models.BooleanField(default=False)),
                ('extrait_naissance_fourni', models.BooleanField(default=False)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=30)),
                ('observations_medicales', models.TextField(blank=True)),
                ('boursier', models.BooleanField(default=False)),
                ('reduction_pourcentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_eleve', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'verbose_name': 'dossier élève',
            },
        ),
        migrations.CreateModel(
            name='EcheanceFrais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200)),
                ('montant_du', models.PositiveIntegerField()),
                ('date_echeance', models.DateField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_frais', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur / Tutrice'), ('autre', 'Autre')], default='tuteur', max_length=10)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'ordering': ['annee_scolaire', 'ordre'],
                'unique_together': {('facility', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant', models.PositiveIntegerField()),
                ('date_paiement', models.DateField()),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('reference_recu', models.CharField(blank=True, max_length=50)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ecole_gestion.echeancefrais')),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='ObservationMontessori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_observation', models.DateField()),
                ('domaine', models.CharField(choices=[('vie_pratique', 'Vie pratique'), ('sensoriel', 'Sensoriel'), ('langage', 'Langage'), ('mathematiques', 'Mathématiques'), ('culture', 'Culture')], max_length=20)),
                ('activite', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('presente', 'Présenté'), ('en_cours', "En cours d'acquisition"), ('acquis', 'Acquis'), ('maitrise', 'Maîtrisé')], default='presente', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('educateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_montessori', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
            ],
            options={
                'ordering': ['-date_observation'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('matiere', models.CharField(max_length=100)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('appreciation', models.CharField(blank=True, max_length=200)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ecole', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ecole_gestion.periode')),
            ],
            options={
                'ordering': ['matiere'],
            },
        ),
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=200)),
                ('missions', models.TextField(blank=True)),
                ('responsabilites', models.TextField(blank=True)),
                ('competences_requises', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kalanfaauth.facility')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_poste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fiche de poste',
            },
        ),
        migrations.CreateModel(
            name='DossierTuteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_tuteurs', to='ecole_gestion.dossiereleve')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_dossiers', to='ecole_gestion.tuteur')),
            ],
            options={
                'unique_together': {('dossier', 'tuteur')},
            },
        ),
    ]
