# Generated by Django 1.9.13 on 2018-02-22 20:44
from django.db import migrations

import kalanfa.core.auth.models


class Migration(migrations.Migration):
    dependencies = [("kalanfaauth", "0007_auto_20171226_1125")]

    operations = [
        migrations.AlterModelManagers(
            name="facilityuser",
            managers=[("objects", kalanfa.core.auth.models.FacilityUserModelManager())],
        )
    ]
