# Generated by Django 1.11.29 on 2022-07-25 09:14
from django.db import migrations

import kalanfa.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0019_collection_no_mptt"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydataset",
            name="extra_fields",
            field=kalanfa.core.fields.JSONField(blank=True, null=True),
        ),
    ]
