# Generated by Django 1.11.29 on 2023-01-31 18:19
from django.db import migrations

import kalanfa.core.fields
import kalanfa.core.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0020_facilitydataset_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitydataset",
            name="extra_fields",
            field=kalanfa.core.fields.JSONField(
                blank=True,
                default={"facility": {}, "on_my_own_setup": False, "pin_code": 0},
                null=True,
                validators=[
                    kalanfa.core.utils.validators.JSON_Schema_Validator(
                        {
                            "additionalProperties": False,
                            "properties": {
                                "facility": {"type": "object"},
                                "on_my_own_setup": {"type": "boolean"},
                                "pin_code": {"type": "integer"},
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
