# Generated by Django 1.11.29 on 2023-03-07 20:46
from django.db import migrations

import kalanfa.core.fields
import kalanfa.core.utils.validators
from kalanfa.core.auth.models import extra_fields_default_values
from kalanfa.core.auth.models import extra_fields_schema


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0022_facilitydataset_extra_fields_update_pin_to_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitydataset",
            name="extra_fields",
            field=kalanfa.core.fields.JSONField(
                blank=True,
                default=extra_fields_default_values,
                null=True,
                validators=[
                    kalanfa.core.utils.validators.JSON_Schema_Validator(
                        extra_fields_schema
                    )
                ],
            ),
        ),
    ]
