# Generated by Django 3.2.25 on 2024-07-16 00:43
from django.db import migrations

import kalanfa.core.auth.constants.demographics
import kalanfa.core.fields
import kalanfa.core.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0026_update_language_code_nyn_to_ny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitydataset",
            name="extra_fields",
            field=kalanfa.core.fields.JSONField(
                blank=True,
                default={"facility": {}, "on_my_own_setup": False, "pin_code": ""},
                null=True,
                validators=[
                    kalanfa.core.utils.validators.JSON_Schema_Validator(
                        {
                            "properties": {
                                "demographic_fields": {
                                    "items": {
                                        "properties": {
                                            "description": {"type": "string"},
                                            "enumValues": {
                                                "items": {
                                                    "properties": {
                                                        "defaultLabel": {
                                                            "type": "string"
                                                        },
                                                        "translations": {
                                                            "items": {
                                                                "properties": {
                                                                    "language": {
                                                                        "enum": [
                                                                            "ar",
                                                                            "bg-bg",
                                                                            "bn-bd",
                                                                            "de",
                                                                            "el",
                                                                            "en",
                                                                            "es-419",
                                                                            "es-es",
                                                                            "fa",
                                                                            "ff-cm",
                                                                            "fr-fr",
                                                                            "gu-in",
                                                                            "ha",
                                                                            "hi-in",
                                                                            "ht",
                                                                            "id",
                                                                            "it",
                                                                            "ka",
                                                                            "km",
                                                                            "ko",
                                                                            "mr",
                                                                            "my",
                                                                            "ny",
                                                                            "pa",
                                                                            "pt-br",
                                                                            "pt-mz",
                                                                            "sw-tz",
                                                                            "te",
                                                                            "uk",
                                                                            "ur-pk",
                                                                            "vi",
                                                                            "yo",
                                                                            "zh-hans",
                                                                        ],
                                                                        "type": "string",
                                                                    },
                                                                    "message": {
                                                                        "type": "string"
                                                                    },
                                                                },
                                                                "type": "object",
                                                            },
                                                            "optional": True,
                                                            "type": "array",
                                                        },
                                                        "value": {"type": "string"},
                                                    },
                                                    "type": "object",
                                                },
                                                "type": "array",
                                            },
                                            "id": {"type": "string"},
                                            "translations": {
                                                "items": {
                                                    "properties": {
                                                        "language": {
                                                            "enum": [
                                                                "ar",
                                                                "bg-bg",
                                                                "bn-bd",
                                                                "de",
                                                                "el",
                                                                "en",
                                                                "es-419",
                                                                "es-es",
                                                                "fa",
                                                                "ff-cm",
                                                                "fr-fr",
                                                                "gu-in",
                                                                "ha",
                                                                "hi-in",
                                                                "ht",
                                                                "id",
                                                                "it",
                                                                "ka",
                                                                "km",
                                                                "ko",
                                                                "mr",
                                                                "my",
                                                                "ny",
                                                                "pa",
                                                                "pt-br",
                                                                "pt-mz",
                                                                "sw-tz",
                                                                "te",
                                                                "uk",
                                                                "ur-pk",
                                                                "vi",
                                                                "yo",
                                                                "zh-hans",
                                                            ],
                                                            "type": "string",
                                                        },
                                                        "message": {"type": "string"},
                                                    },
                                                    "type": "object",
                                                },
                                                "optional": True,
                                                "type": "array",
                                            },
                                        },
                                        "type": "object",
                                    },
                                    "optional": True,
                                    "type": "array",
                                },
                                "facility": {"optional": True, "type": "object"},
                                "on_my_own_setup": {
                                    "optional": True,
                                    "type": "boolean",
                                },
                                "pin_code": {
                                    "optional": True,
                                    "type": ["string", "null"],
                                },
                            },
                            "type": "object",
                        }
                    ),
                    kalanfa.core.auth.constants.demographics.UniqueIdsValidator(
                        "demographic_fields"
                    ),
                    kalanfa.core.auth.constants.demographics.DescriptionTranslationValidator(
                        "demographic_fields"
                    ),
                    kalanfa.core.auth.constants.demographics.EnumValuesValidator(
                        "demographic_fields"
                    ),
                    kalanfa.core.auth.constants.demographics.LabelTranslationValidator(
                        "demographic_fields"
                    ),
                ],
            ),
        ),
    ]
