# Generated by Django 3.2.25 on 2025-05-30 16:29
from django.db import migrations

import kalanfa.core.auth.models


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0028_facilityuser_date_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="facilityuser",
            managers=[
                ("objects", kalanfa.core.auth.models.FacilityUserModelManager()),
                (
                    "soft_deleted_objects",
                    kalanfa.core.auth.models.SoftDeletedFacilityUserModelManager(),
                ),
            ],
        ),
    ]
