# Generated by Django 3.2.25 on 2025-06-03 11:12
from django.db import migrations

import kalanfa.core.auth.models


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0029_alter_facilityuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="facilityuser",
            managers=[
                (
                    "all_objects",
                    kalanfa.core.auth.models.AllObjectsFacilityUserModelManager(),
                ),
                ("objects", kalanfa.core.auth.models.FacilityUserModelManager()),
                (
                    "soft_deleted_objects",
                    kalanfa.core.auth.models.SoftDeletedFacilityUserModelManager(),
                ),
            ],
        ),
    ]
