# Generated by Django 3.2.25 on 2025-10-30 01:01
from django.db import migrations

import kalanfa.core.auth.models


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0031_session"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="facilityuser",
            managers=[
                (
                    "all_objects",
                    kalanfa.core.auth.models.AllObjectsFacilityUserModelManager(),
                ),
                ("objects", kalanfa.core.auth.models.FacilityUserModelManager()),
                (
                    "syncing_objects",
                    kalanfa.core.auth.models.BaseFacilityUserModelManager(),
                ),
                (
                    "soft_deleted_objects",
                    kalanfa.core.auth.models.SoftDeletedFacilityUserModelManager(),
                ),
            ],
        ),
    ]
