import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import{api,DEFAULT_BASE_URL,getSettings,saveSettings,type CaptureMode,type Project}from"../shared";import"./styles.css";
type Job={id:string;status:string;document_id:string|null;error_message:string|null};
function App(){const[baseUrl,setBaseUrl]=useState(DEFAULT_BASE_URL),[token,setToken]=useState(""),[connected,setConnected]=useState(false),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[mode,setMode]=useState<CaptureMode>("visible"),[status,setStatus]=useState("Configure your connection."),[busy,setBusy]=useState(false),[documentId,setDocumentId]=useState("");
useEffect(()=>{void getSettings().then(s=>{setBaseUrl(s.baseUrl);setToken(s.token);if(s.token)void connect(s)})},[]);
async function connect(settings={baseUrl,token}){setBusy(true);try{await saveSettings(settings);await api("/api/extension/me");const p=await api<{projects:Project[]}>("/api/extension/projects");setProjects(p.projects);setConnected(true);setStatus("Connected and ready to capture.");}catch(e){setConnected(false);setStatus(e instanceof Error?e.message:"Connection failed");}finally{setBusy(false)}}
async function capture(){setBusy(true);setDocumentId("");try{setStatus("Capturing the active tab…");const type=mode==="visible"?"CAPTURE_VISIBLE":mode==="region"?"CAPTURE_REGION":"CAPTURE_FULL_PAGE";const result=await chrome.runtime.sendMessage({type});if(!result?.ok)throw new Error(result?.error||"Capture failed");let blob:Blob;if(result.segments)blob=await stitch(result.segments,result.metrics);else blob=await crop(result.dataUrl,result.crop,result.devicePixelRatio);const form=new FormData();form.append("file",blob,`capture-${Date.now()}.png`);form.append("projectId",projectId);form.append("pageUrl",result.url);form.append("pageTitle",result.title);form.append("captureMode",mode);setStatus("Uploading and starting AI generation…");const created=await api<{jobId:string}>("/api/extension/captures",{method:"POST",body:form});await poll(created.jobId);}catch(e){setStatus(e instanceof Error?e.message:"Capture failed");}finally{setBusy(false)}}
async function poll(id:string){for(let i=0;i<90;i++){const{job}=await api<{job:Job}>(`/api/extension/jobs/${id}`);setStatus(`Generation status: ${job.status}`);if(job.status==="completed"&&job.document_id){setDocumentId(job.document_id);setStatus("Your document is ready.");return;}if(job.status==="failed")throw new Error(job.error_message||"AI generation failed");await new Promise(r=>setTimeout(r,2000));}throw new Error("Generation is still running. Open the web app to continue tracking it.")}
async function openDoc(){const s=await getSettings();chrome.tabs.create({url:`${s.baseUrl.replace(/\/$/,"")}/documents/${documentId}`})}
return <main><header><div className="logo">AD</div><div><h1>AI Documentation</h1><p>Capture → generate → edit</p></div></header>{!connected?<section><label>Web app URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="http://localhost:3000"/></label><label>Extension token<textarea value={token} onChange={e=>setToken(e.target.value)} rows={3}/></label><button disabled={busy||!token} onClick={()=>connect()}>Connect</button><small>Create a scoped token in Web App → Settings.</small></section>:<section><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Capture mode<select value={mode} onChange={e=>setMode(e.target.value as CaptureMode)}><option value="visible">Visible tab</option><option value="region">Select region</option><option value="full_page">Full page (experimental)</option></select></label><button disabled={busy} onClick={capture}>{busy?"Working…":"Capture and generate"}</button>{documentId?<button className="secondary" onClick={openDoc}>Open document</button>:null}<button className="link" onClick={()=>{setConnected(false);setStatus("Update connection settings.")}}>Connection settings</button></section>}<footer>{status}</footer></main>}
async function image(url:string){const i=new Image();i.src=url;await i.decode();return i}async function crop(dataUrl:string,rect?:{x:number;y:number;width:number;height:number},dpr=1){if(!rect)return(await fetch(dataUrl)).blob();const i=await image(dataUrl);const c=document.createElement("canvas");c.width=Math.round(rect.width*dpr);c.height=Math.round(rect.height*dpr);c.getContext("2d")!.drawImage(i,rect.x*dpr,rect.y*dpr,rect.width*dpr,rect.height*dpr,0,0,c.width,c.height);return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("Could not crop image")),"image/png"))}async function stitch(segments:string[],m:any){const imgs=await Promise.all(segments.map(image));const dpr=m.devicePixelRatio||1,c=document.createElement("canvas");c.width=Math.round(m.viewportWidth*dpr);c.height=Math.round(m.scrollHeight*dpr);const ctx=c.getContext("2d")!;imgs.forEach((img,i)=>{const y=i*m.viewportHeight*dpr;const remaining=c.height-y;ctx.drawImage(img,0,0,img.width,Math.min(img.height,remaining),0,y,c.width,Math.min(img.height,remaining))});return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("Could not stitch page")),"image/png"))}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
