# Generated by Django 1.11.28 on 2020-05-20 14:56
from django.db import migrations

import kalanfa.core.fields


class Migration(migrations.Migration):
    dependencies = [("content", "0025_add_h5p_kind")]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="options",
            field=kalanfa.core.fields.JSONField(blank=True, default={}, null=True),
        )
    ]
