# Generated by Django 1.11.8 on 2018-02-21 19:15
import django.db.models.deletion
from django.db import migrations
from django.db import models

import kalanfa.core.fields
import kalanfa.utils.time_utils


class Migration(migrations.Migration):
    dependencies = [("lessons", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="lesson", old_name="name", new_name="title"),
        migrations.RemoveField(model_name="lesson", name="is_archived"),
        migrations.AddField(
            model_name="lesson",
            name="date_created",
            field=kalanfa.core.fields.DateTimeTzField(
                default=kalanfa.utils.time_utils.local_now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="lessonassignment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_assignments",
                to="lessons.Lesson",
            ),
        ),
    ]
