# Generated by Django 1.11.29 on 2021-07-24 00:12
import django.db.models.deletion
import morango.models.fields.uuids
from django.conf import settings
from django.db import migrations
from django.db import models

import kalanfa.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kalanfaauth", "0019_collection_no_mptt"),
        ("lessons", "0002_auto_20180221_1115"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualSyncableLesson",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                ("lesson_id", models.UUIDField()),
                ("serialized_lesson", kalanfa.core.fields.JSONField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kalanfaauth.Collection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kalanfaauth.FacilityDataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kalanfaauth.FacilityUser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
